const dataCalendars = [
  {
    "date": "01/05/2025",
    "time": "5:00am",
    "currency": "USD",
    "impact": "orange",
    "event": "President Trump Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "All Day",
    "currency": "CNY",
    "impact": "gray",
    "event": "Bank Holiday",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "5:30am",
    "currency": "JPY",
    "impact": "yellow",
    "event": "Final Manufacturing PMI",
    "actual": 48.7,
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "6:30am",
    "currency": "AUD",
    "impact": "yellow",
    "event": "Goods Trade Balance",
    "actual": "6.90B",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "",
    "currency": "AUD",
    "impact": "yellow",
    "event": "Import Prices q/q",
    "actual": "3.3%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "8:03am",
    "currency": "JPY",
    "impact": "red",
    "event": "BOJ Outlook Report",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "",
    "currency": "JPY",
    "impact": "red",
    "event": "BOJ Policy Rate",
    "actual": "<0.50%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "",
    "currency": "JPY",
    "impact": "red",
    "event": "Monetary Policy Statement",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "10:00am",
    "currency": "JPY",
    "impact": "yellow",
    "event": "Consumer Confidence",
    "actual": 31.2,
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "All Day",
    "currency": "CHF",
    "impact": "gray",
    "event": "Bank Holiday",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "All Day",
    "currency": "EUR",
    "impact": "gray",
    "event": "French Bank Holiday",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "All Day",
    "currency": "EUR",
    "impact": "gray",
    "event": "German Bank Holiday",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "All Day",
    "currency": "EUR",
    "impact": "gray",
    "event": "Italian Bank Holiday",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "11:30am",
    "currency": "AUD",
    "impact": "yellow",
    "event": "Commodity Prices y/y",
    "actual": "-6.1%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "",
    "currency": "CHF",
    "impact": "yellow",
    "event": "Retail Sales y/y",
    "actual": "2.2%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "",
    "currency": "JPY",
    "impact": "red",
    "event": "BOJ Press Conference",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "1:30pm",
    "currency": "GBP",
    "impact": "yellow",
    "event": "Final Manufacturing PMI",
    "actual": 45.4,
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "yellow",
    "event": "M4 Money Supply m/m",
    "actual": "0.3%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "yellow",
    "event": "Mortgage Approvals",
    "actual": "64K",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "1:32pm",
    "currency": "GBP",
    "impact": "yellow",
    "event": "Net Lending to Individuals m/m",
    "actual": "13.8B",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "4:30pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "Challenger Job Cuts y/y",
    "actual": "62.7%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "5:30pm",
    "currency": "USD",
    "impact": "red",
    "event": "Unemployment Claims",
    "actual": "241K",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "6:30pm",
    "currency": "CAD",
    "impact": "yellow",
    "event": "Manufacturing PMI",
    "actual": 45.3,
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "6:45pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "Final Manufacturing PMI",
    "actual": 50.2,
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "7:00pm",
    "currency": "USD",
    "impact": "red",
    "event": "ISM Manufacturing PMI",
    "actual": 48.7,
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "orange",
    "event": "ISM Manufacturing Prices",
    "actual": 69.8,
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "yellow",
    "event": "Construction Spending m/m",
    "actual": "-0.5%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "All Day",
    "currency": "USD",
    "impact": "yellow",
    "event": "Wards Total Vehicle Sales",
    "actual": "17.3M",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "01/05/2025",
    "time": "11:00pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "Natural Gas Storage",
    "actual": "107B",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "02/05/2025",
    "time": "3:45am",
    "currency": "NZD",
    "impact": "yellow",
    "event": "Building Consents m/m",
    "actual": "9.6%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "4:30am",
    "currency": "JPY",
    "impact": "yellow",
    "event": "Unemployment Rate",
    "actual": "2.5%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "4:50am",
    "currency": "JPY",
    "impact": "yellow",
    "event": "Monetary Base y/y",
    "actual": "-4.8%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "All Day",
    "currency": "CNY",
    "impact": "gray",
    "event": "Bank Holiday",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "6:30am",
    "currency": "AUD",
    "impact": "orange",
    "event": "Retail Sales m/m",
    "actual": "0.3%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "",
    "currency": "AUD",
    "impact": "yellow",
    "event": "PPI q/q",
    "actual": "0.9%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "11:45am",
    "currency": "EUR",
    "impact": "yellow",
    "event": "French Gov Budget Balance",
    "actual": "-47.0B",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "12:15pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Spanish Manufacturing PMI",
    "actual": 48.1,
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "12:30pm",
    "currency": "CHF",
    "impact": "yellow",
    "event": "Manufacturing PMI",
    "actual": 45.8,
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "12:45pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Italian Manufacturing PMI",
    "actual": 49.3,
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "12:50pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "French Final Manufacturing PMI",
    "actual": 48.7,
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "12:55pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "German Final Manufacturing PMI",
    "actual": 48.4,
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "1:00pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Final Manufacturing PMI",
    "actual": 49,
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Italian Monthly Unemployment Rate",
    "actual": "6.0%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "2:00pm",
    "currency": "EUR",
    "impact": "orange",
    "event": "Core CPI Flash Estimate y/y",
    "actual": "2.7%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "",
    "currency": "EUR",
    "impact": "orange",
    "event": "CPI Flash Estimate y/y",
    "actual": "2.2%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "",
    "currency": "EUR",
    "impact": "yellow",
    "event": "ECB Economic Bulletin",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Unemployment Rate",
    "actual": "6.2%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "5:30pm",
    "currency": "USD",
    "impact": "red",
    "event": "Average Hourly Earnings m/m",
    "actual": "0.2%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "red",
    "event": "Non-Farm Employment Change",
    "actual": "177K",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "red",
    "event": "Unemployment Rate",
    "actual": "4.2%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "02/05/2025",
    "time": "7:00pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "Factory Orders m/m",
    "actual": "4.3%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "03/05/2025",
    "time": "All Day",
    "currency": "AUD",
    "impact": "red",
    "event": "Parliamentary Elections",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Sat"
  },
  {
    "date": "03/05/2025",
    "time": "All Day",
    "currency": "All",
    "impact": "orange",
    "event": "OPEC-JMMC Meetings",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Sat"
  },
  {
    "date": "05/05/2025",
    "time": "All Day",
    "currency": "JPY",
    "impact": "gray",
    "event": "Bank Holiday",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "05/05/2025",
    "time": "6:00am",
    "currency": "AUD",
    "impact": "yellow",
    "event": "MI Inflation Gauge m/m",
    "actual": "0.6%",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "05/05/2025",
    "time": "6:30am",
    "currency": "AUD",
    "impact": "yellow",
    "event": "ANZ Job Advertisements m/m",
    "actual": "0.5%",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "05/05/2025",
    "time": "11:30am",
    "currency": "CHF",
    "impact": "red",
    "event": "CPI m/m",
    "actual": "0.0%",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "05/05/2025",
    "time": "All Day",
    "currency": "GBP",
    "impact": "gray",
    "event": "Bank Holiday",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "05/05/2025",
    "time": "1:30pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Sentix Investor Confidence",
    "actual": -8.1,
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "05/05/2025",
    "time": "6:45pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "Final Services PMI",
    "actual": 50.8,
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "05/05/2025",
    "time": "7:00pm",
    "currency": "USD",
    "impact": "red",
    "event": "ISM Services PMI",
    "actual": 51.6,
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "06/05/2025",
    "time": "All Day",
    "currency": "JPY",
    "impact": "gray",
    "event": "Bank Holiday",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "6:00am",
    "currency": "NZD",
    "impact": "yellow",
    "event": "ANZ Commodity Prices m/m",
    "actual": "0.0%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "6:30am",
    "currency": "AUD",
    "impact": "yellow",
    "event": "Building Approvals m/m",
    "actual": "-8.8%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "6:45am",
    "currency": "CNY",
    "impact": "yellow",
    "event": "Caixin Services PMI",
    "actual": 50.7,
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "10:45am",
    "currency": "CHF",
    "impact": "yellow",
    "event": "Unemployment Rate",
    "actual": "2.8%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "11:45am",
    "currency": "EUR",
    "impact": "yellow",
    "event": "French Industrial Production m/m",
    "actual": "0.2%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "12:00pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Spanish Unemployment Change",
    "actual": "-67.4K",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "12:15pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Spanish Services PMI",
    "actual": 53.4,
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "12:35pm",
    "currency": "CHF",
    "impact": "orange",
    "event": "SNB Chairman Schlegel Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "12:45pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Italian Services PMI",
    "actual": 52.9,
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "12:50pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "French Final Services PMI",
    "actual": 47.3,
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "12:55pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "German Final Services PMI",
    "actual": 49,
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "1:00pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Final Services PMI",
    "actual": 50.1,
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "1:30pm",
    "currency": "GBP",
    "impact": "yellow",
    "event": "Final Services PMI",
    "actual": 49,
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "2:00pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "PPI m/m",
    "actual": "-1.6%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "5:30pm",
    "currency": "CAD",
    "impact": "yellow",
    "event": "Trade Balance",
    "actual": "-0.5B",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "yellow",
    "event": "Trade Balance",
    "actual": "-140.5B",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "7:00pm",
    "currency": "CAD",
    "impact": "orange",
    "event": "Ivey PMI",
    "actual": 47.9,
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "7:06pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "RCM/TIPP Economic Optimism",
    "actual": 47.9,
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "8:34pm",
    "currency": "NZD",
    "impact": "yellow",
    "event": "GDT Price Index",
    "actual": "4.6%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "06/05/2025",
    "time": "10:01pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "10-y Bond Auction",
    "actual": "4.34|2.6",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "07/05/2025",
    "time": "1:30am",
    "currency": "USD",
    "impact": "yellow",
    "event": "API Weekly Statistical Bulletin",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "2:00am",
    "currency": "NZD",
    "impact": "yellow",
    "event": "RBNZ Financial Stability Report",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "3:45am",
    "currency": "NZD",
    "impact": "red",
    "event": "Employment Change q/q",
    "actual": "0.1%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "",
    "currency": "NZD",
    "impact": "red",
    "event": "Unemployment Rate",
    "actual": "5.1%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "",
    "currency": "NZD",
    "impact": "yellow",
    "event": "Labor Cost Index q/q",
    "actual": "0.4%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "6:00am",
    "currency": "NZD",
    "impact": "orange",
    "event": "RBNZ Gov Hawkesby Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "11:00am",
    "currency": "EUR",
    "impact": "yellow",
    "event": "German Factory Orders m/m",
    "actual": "3.6%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "11:45am",
    "currency": "EUR",
    "impact": "yellow",
    "event": "French Prelim Private Payrolls q/q",
    "actual": "0.0%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "",
    "currency": "EUR",
    "impact": "yellow",
    "event": "French Trade Balance",
    "actual": "-6.2B",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "12:00pm",
    "currency": "CHF",
    "impact": "yellow",
    "event": "Foreign Currency Reserves",
    "actual": "703B",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "1:00pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Italian Retail Sales m/m",
    "actual": "-0.5%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "1:30pm",
    "currency": "GBP",
    "impact": "orange",
    "event": "Construction PMI",
    "actual": 46.6,
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "1:57pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "French 10-y Bond Auction",
    "actual": "3.24|2.8",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "2:00pm",
    "currency": "CHF",
    "impact": "yellow",
    "event": "Gov Board Member Tschudin Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Retail Sales m/m",
    "actual": "-0.1%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "7:30pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "Crude Oil Inventories",
    "actual": "-2.0M",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "11:00pm",
    "currency": "USD",
    "impact": "red",
    "event": "Federal Funds Rate",
    "actual": "4.50%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "red",
    "event": "FOMC Statement",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "07/05/2025",
    "time": "11:30pm",
    "currency": "USD",
    "impact": "red",
    "event": "FOMC Press Conference",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "08/05/2025",
    "time": "12:00am",
    "currency": "USD",
    "impact": "yellow",
    "event": "Consumer Credit m/m",
    "actual": "10.2B",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "4:01am",
    "currency": "GBP",
    "impact": "yellow",
    "event": "RICS House Price Balance",
    "actual": "-3%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "4:50am",
    "currency": "JPY",
    "impact": "yellow",
    "event": "Monetary Policy Meeting Minutes",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "8:35am",
    "currency": "JPY",
    "impact": "yellow",
    "event": "10-y Bond Auction",
    "actual": "1.27|2.5",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "11:00am",
    "currency": "EUR",
    "impact": "yellow",
    "event": "German Industrial Production m/m",
    "actual": "3.0%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "",
    "currency": "EUR",
    "impact": "yellow",
    "event": "German Trade Balance",
    "actual": "21.1B",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "yellow",
    "event": "Halifax HPI m/m",
    "actual": "0.3%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "All Day",
    "currency": "EUR",
    "impact": "gray",
    "event": "French Bank Holiday",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "4:02pm",
    "currency": "GBP",
    "impact": "red",
    "event": "BOE Monetary Policy Report",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "red",
    "event": "Monetary Policy Summary",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "red",
    "event": "MPC Official Bank Rate Votes",
    "actual": "0-7-2",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "red",
    "event": "Official Bank Rate",
    "actual": "4.25%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "4:30pm",
    "currency": "GBP",
    "impact": "red",
    "event": "BOE Gov Bailey Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "5:30pm",
    "currency": "USD",
    "impact": "red",
    "event": "Unemployment Claims",
    "actual": "228K",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "yellow",
    "event": "Prelim Nonfarm Productivity q/q",
    "actual": "-0.8%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "yellow",
    "event": "Prelim Unit Labor Costs q/q",
    "actual": "5.7%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "7:00pm",
    "currency": "CAD",
    "impact": "yellow",
    "event": "BOC Financial System Review",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "red",
    "event": "President Trump Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "yellow",
    "event": "Final Wholesale Inventories m/m",
    "actual": "0.4%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "7:30pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "Natural Gas Storage",
    "actual": "104B",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "8:00pm",
    "currency": "CAD",
    "impact": "red",
    "event": "BOC Press Conference",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "08/05/2025",
    "time": "10:01pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "30-y Bond Auction",
    "actual": "4.82|2.3",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "09/05/2025",
    "time": "4:30am",
    "currency": "JPY",
    "impact": "yellow",
    "event": "Average Cash Earnings y/y",
    "actual": "2.1%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "",
    "currency": "JPY",
    "impact": "yellow",
    "event": "Household Spending y/y",
    "actual": "2.1%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "8:04am",
    "currency": "CNY",
    "impact": "yellow",
    "event": "Trade Balance",
    "actual": "690B",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "8:06am",
    "currency": "CNY",
    "impact": "yellow",
    "event": "USD-Denominated Trade Balance",
    "actual": "96.2B",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "10:00am",
    "currency": "JPY",
    "impact": "yellow",
    "event": "Leading Indicators",
    "actual": "107.7%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "12:00pm",
    "currency": "CHF",
    "impact": "yellow",
    "event": "SECO Consumer Climate",
    "actual": -42,
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "1:00pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Italian Industrial Production m/m",
    "actual": "0.1%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "1:40pm",
    "currency": "GBP",
    "impact": "red",
    "event": "BOE Gov Bailey Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "2:55pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "FOMC Member Barr Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "3:45pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "FOMC Member Kugler Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "4:15pm",
    "currency": "GBP",
    "impact": "yellow",
    "event": "MPC Member Pill Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "5:30pm",
    "currency": "CAD",
    "impact": "red",
    "event": "Employment Change",
    "actual": "7.4K",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "",
    "currency": "CAD",
    "impact": "red",
    "event": "Unemployment Rate",
    "actual": "6.9%",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "yellow",
    "event": "FOMC Member Barkin Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "yellow",
    "event": "FOMC Member Williams Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "7:00pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "FOMC Member Goolsbee Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "8:30pm",
    "currency": "USD",
    "impact": "orange",
    "event": "FOMC Member Waller Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "09/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "yellow",
    "event": "FOMC Member Williams Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Fri"
  },
  {
    "date": "10/05/2025",
    "time": "4:45am",
    "currency": "USD",
    "impact": "yellow",
    "event": "FOMC Member Cook Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Sat"
  },
  {
    "date": "10/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "yellow",
    "event": "FOMC Member Hammack Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Sat"
  },
  {
    "date": "10/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "yellow",
    "event": "FOMC Member Musalem Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Sat"
  },
  {
    "date": "10/05/2025",
    "time": "6:30am",
    "currency": "CNY",
    "impact": "orange",
    "event": "CPI y/y",
    "actual": "-0.1%",
    "forecast": "",
    "previous": "",
    "day": "Sat"
  },
  {
    "date": "10/05/2025",
    "time": "",
    "currency": "CNY",
    "impact": "orange",
    "event": "PPI y/y",
    "actual": "-2.7%",
    "forecast": "",
    "previous": "",
    "day": "Sat"
  },
  {
    "date": "11/05/2025",
    "time": "11:00pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "FOMC Member Barkin Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Sun"
  },
  {
    "date": "12/05/2025",
    "time": "4:50am",
    "currency": "JPY",
    "impact": "yellow",
    "event": "Bank Lending y/y",
    "actual": "2.4%",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "12/05/2025",
    "time": "",
    "currency": "JPY",
    "impact": "yellow",
    "event": "Current Account",
    "actual": "2.72T",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "12/05/2025",
    "time": "10:00am",
    "currency": "JPY",
    "impact": "yellow",
    "event": "Economy Watchers Sentiment",
    "actual": 42.6,
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "12/05/2025",
    "time": "1:00pm",
    "currency": "GBP",
    "impact": "yellow",
    "event": "MPC Member Lombardelli Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "12/05/2025",
    "time": "All Day",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Eurogroup Meetings",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "12/05/2025",
    "time": "3:30pm",
    "currency": "GBP",
    "impact": "yellow",
    "event": "MPC Member Greene Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "12/05/2025",
    "time": "5:50pm",
    "currency": "GBP",
    "impact": "yellow",
    "event": "MPC Member Mann Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "12/05/2025",
    "time": "6:30pm",
    "currency": "USD",
    "impact": "orange",
    "event": "President Trump Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "12/05/2025",
    "time": "6:45pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "Cleveland Fed Inflation Expectations",
    "actual": "3.9%",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "12/05/2025",
    "time": "7:25pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "FOMC Member Kugler Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "12/05/2025",
    "time": "9:00pm",
    "currency": "GBP",
    "impact": "yellow",
    "event": "MPC Member Taylor Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "12/05/2025",
    "time": "11:00pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "Federal Budget Balance",
    "actual": "258.4B",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "12/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "yellow",
    "event": "Loan Officer Survey",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Mon"
  },
  {
    "date": "13/05/2025",
    "time": "4:01am",
    "currency": "GBP",
    "impact": "yellow",
    "event": "BRC Retail Sales Monitor y/y",
    "actual": "6.8%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "4:50am",
    "currency": "JPY",
    "impact": "yellow",
    "event": "BOJ Summary of Opinions",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "",
    "currency": "JPY",
    "impact": "yellow",
    "event": "M2 Money Stock y/y",
    "actual": "0.5%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "5:26am",
    "currency": "AUD",
    "impact": "yellow",
    "event": "Westpac Consumer Sentiment",
    "actual": "2.2%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "6:30am",
    "currency": "AUD",
    "impact": "yellow",
    "event": "NAB Business Confidence",
    "actual": -1,
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "8:35am",
    "currency": "JPY",
    "impact": "yellow",
    "event": "30-y Bond Auction",
    "actual": "2.94|3.1",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "11:00am",
    "currency": "GBP",
    "impact": "red",
    "event": "Claimant Count Change",
    "actual": "5.2K",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "orange",
    "event": "Average Earnings Index 3m/y",
    "actual": "5.5%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "yellow",
    "event": "Unemployment Rate",
    "actual": "4.5%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "All Day",
    "currency": "EUR",
    "impact": "yellow",
    "event": "ECOFIN Meetings",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "1:45pm",
    "currency": "GBP",
    "impact": "yellow",
    "event": "MPC Member Pill Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "2:00pm",
    "currency": "EUR",
    "impact": "orange",
    "event": "German ZEW Economic Sentiment",
    "actual": 25.2,
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "",
    "currency": "EUR",
    "impact": "yellow",
    "event": "ZEW Economic Sentiment",
    "actual": 11.6,
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "3:00pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "NFIB Small Business Index",
    "actual": 95.8,
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "5:30pm",
    "currency": "USD",
    "impact": "red",
    "event": "Core CPI m/m",
    "actual": "0.2%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "red",
    "event": "CPI m/m",
    "actual": "0.2%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "red",
    "event": "CPI y/y",
    "actual": "2.3%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "6:30pm",
    "currency": "GBP",
    "impact": "yellow",
    "event": "CB Leading Index m/m",
    "actual": "-0.4%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "7:00pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "Mortgage Delinquencies",
    "actual": "4.04%",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "8:00pm",
    "currency": "GBP",
    "impact": "red",
    "event": "BOE Gov Bailey Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "13/05/2025",
    "time": "8:34pm",
    "currency": "USD",
    "impact": "orange",
    "event": "President Trump Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Tue"
  },
  {
    "date": "14/05/2025",
    "time": "1:30am",
    "currency": "USD",
    "impact": "yellow",
    "event": "API Weekly Statistical Bulletin",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "3:45am",
    "currency": "NZD",
    "impact": "yellow",
    "event": "Visitor Arrivals m/m",
    "actual": "-1.9%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "4:50am",
    "currency": "JPY",
    "impact": "yellow",
    "event": "PPI y/y",
    "actual": "4.0%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "6:30am",
    "currency": "AUD",
    "impact": "red",
    "event": "Wage Price Index q/q",
    "actual": "0.9%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "11:00am",
    "currency": "EUR",
    "impact": "yellow",
    "event": "German Final CPI m/m",
    "actual": "0.4%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "12:15pm",
    "currency": "GBP",
    "impact": "yellow",
    "event": "MPC Member Breeden Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "1:15pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "German Buba President Nagel Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "2:02pm",
    "currency": "CNY",
    "impact": "yellow",
    "event": "M2 Money Supply y/y",
    "actual": "8.0%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "2:03pm",
    "currency": "CNY",
    "impact": "orange",
    "event": "New Loans",
    "actual": "280B",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "yellow",
    "event": "10-y Bond Auction",
    "actual": "4.67|3.1",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "2:15pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "FOMC Member Waller Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "2:38pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "German 30-y Bond Auction",
    "actual": "3.12|2.3",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "5:30pm",
    "currency": "CAD",
    "impact": "yellow",
    "event": "Building Permits m/m",
    "actual": "-4.1%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "6:10pm",
    "currency": "USD",
    "impact": "yellow",
    "event": "FOMC Member Jefferson Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "7:30pm",
    "currency": "AUD",
    "impact": "yellow",
    "event": "CB Leading Index m/m",
    "actual": "-0.4%",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "14/05/2025",
    "time": "",
    "currency": "USD",
    "impact": "yellow",
    "event": "Crude Oil Inventories",
    "actual": "3.5M",
    "forecast": "",
    "previous": "",
    "day": "Wed"
  },
  {
    "date": "15/05/2025",
    "time": "2:40am",
    "currency": "USD",
    "impact": "yellow",
    "event": "FOMC Member Daly Speaks",
    "actual": "",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "3:45am",
    "currency": "NZD",
    "impact": "yellow",
    "event": "FPI m/m",
    "actual": "0.8%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "6:00am",
    "currency": "AUD",
    "impact": "yellow",
    "event": "MI Inflation Expectations",
    "actual": "4.1%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "6:30am",
    "currency": "AUD",
    "impact": "red",
    "event": "Employment Change",
    "actual": "89.0K",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "",
    "currency": "AUD",
    "impact": "red",
    "event": "Unemployment Rate",
    "actual": "4.1%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "10:59am",
    "currency": "JPY",
    "impact": "yellow",
    "event": "Prelim Machine Tool Orders y/y",
    "actual": "7.7%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "11:00am",
    "currency": "EUR",
    "impact": "yellow",
    "event": "German WPI m/m",
    "actual": "-0.1%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "red",
    "event": "GDP m/m",
    "actual": "0.2%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "orange",
    "event": "Prelim GDP q/q",
    "actual": "0.7%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "yellow",
    "event": "Construction Output m/m",
    "actual": "0.5%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "yellow",
    "event": "Goods Trade Balance",
    "actual": "-19.9B",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "yellow",
    "event": "Index of Services 3m/3m",
    "actual": "0.7%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "yellow",
    "event": "Industrial Production m/m",
    "actual": "-0.7%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "yellow",
    "event": "Manufacturing Production m/m",
    "actual": "-0.8%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "",
    "currency": "GBP",
    "impact": "yellow",
    "event": "Prelim Business Investment q/q",
    "actual": "5.9%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "11:30am",
    "currency": "CHF",
    "impact": "yellow",
    "event": "PPI m/m",
    "actual": "0.1%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "11:45am",
    "currency": "EUR",
    "impact": "yellow",
    "event": "French Final CPI m/m",
    "actual": "0.6%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "2:00pm",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Flash Employment Change q/q",
    "actual": "0.3%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Flash GDP q/q",
    "actual": "0.3%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/05/2025",
    "time": "",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Industrial Production m/m",
    "actual": "2.6%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/08/2025",
    "time": "",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Industrial Production m/m",
    "actual": "2.6%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  },
  {
    "date": "15/07/2025",
    "time": "",
    "currency": "EUR",
    "impact": "yellow",
    "event": "Industrial Production m/m",
    "actual": "2.6%",
    "forecast": "",
    "previous": "",
    "day": "Thu"
  }
]

export default dataCalendars